name: Build Python EXE with PyInstaller

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: windows-latest  # Runs the job on a Windows runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version of Python to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Install PyInstaller to compile the script

      - name: Build the EXE
        run: |
          pyinstaller --onefile --noconsole --distpath dist/ --workpath build/ --specpath . checklist.py
      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v2
        with:
          name: pokemon-checklist-exe
          path: dist/pokemon-checklist.exe